### ISSUE TITLE
cost in example 

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet-memonger#3]
Hi, 
 I tried runing both memonger examples using mxnet, however I got same cost for old and new feature map for both examples. Did I miss any parameters in the example code? I saw the threshold in search_plan, but it is set to zero in the function. So I'm wondering how to use this example? Also, is there any example based on the symbol_*.py files? I tried to use memonger in train_cifar10.py.  It crashed on line63 creating shape dict with input out_shapes not iteratable.

**Comment by Godricly** [comment]
@tqchen @pluskid

**Comment by tqchen** [comment]
It is probably due to your version of mxnet was not the lastest. I confirmed these cases on my machine.

**Comment by Godricly** [comment]
Well. I did a sync on Monday. Any debugging strategy for this? it does output different threshold value,but the cost remains the same. Is the set_att function creating a splitting candidate as algorithm 3 in paper or is it enforcing the symbol to be a splitting point? The algorithm looks like visiting checkpoints of maze in video games. ;)

**Comment by tqchen** [comment]
We need the latest version so the attributes pass in. Check if this line get executed https://github.com/dmlc/mxnet/blob/master/src/symbol/static_graph.cc#L429

**Comment by Godricly** [comment]
Ok. The problem was with MXNET_BACKWARD_DO_MIRROR. We set it to 1 so it works now. But the result is not what we expected. The new feature map is bigger than old one. Do you have any log available to compare? 

[memonger]$ python example_lstm.py 
Search threshold=0 MB, cost=13399 MB
Search threshold=164 MB, cost=13401 MB
Search threshold=162 MB, cost=13401 MB
Search threshold=60 MB, cost=13400 MB
Search threshold=93 MB, cost=13400 MB
Search threshold=126 MB, cost=13401 MB
Search threshold=159 MB, cost=13401 MB
Search threshold=192 MB, cost=13402 MB
Search threshold=225 MB, cost=13401 MB
Find best plan with threshold=0, cost=13399 MB
Old feature map cost=11210 MB
New feature map cost=13399 MB

**Comment by tqchen** [comment]
it has nothing to do with MXNET_BACKWARD_DO_MIRROR

**Comment by Godricly** [comment]
I mean we set the environment using export. Previously it can't pass  if (do_mirror == 0) return false.

**Comment by tqchen** [comment]
I have updated the main branch so MXNET_BACKWARD_DO_MIRROR does not matter anymore. It could due to that you switched other env options on. We do need other options to be on default, to turn on all the optimizations

**Comment by Godricly** [comment]
that change works. Thank you.
